USE tkj3_profile;

INSERT INTO siswa (nama_lengkap, nama_panggilan, kelas, keahlian, skill, minat_hobi, cita_cita, deskripsi, foto) VALUES
('Aang Burhanudin Badsah', NULL, 'XI TKJ 3', NULL, NULL, NULL, NULL, NULL, 'aang-burhanudin-badsah.jpg'),
('Adinda Ramadhani', NULL, 'XI TKJ 3', NULL, NULL, NULL, NULL, NULL, 'adinda-ramadhani.jpg'),
('Anantadewa Wiwasata Putra Maharani', NULL, 'XI TKJ 3', NULL, NULL, NULL, NULL, NULL, 'anantadewa-wiwasata-putra-maharani.jpg'),
('Annisa Ramadhani Putri Adiwanto', NULL, 'XI TKJ 3', NULL, NULL, NULL, NULL, NULL, 'annisa-ramadhani-putri-adiwanto.jpg'),
('Ariel Ardanta Nurrohman Reyhandy', NULL, 'XI TKJ 3', NULL, NULL, NULL, NULL, NULL, 'ariel-ardanta-nurrohman-reyhandy.jpg'),
('Bima Gusto Mahatsafa', NULL, 'XI TKJ 3', NULL, NULL, NULL, NULL, NULL, 'bima-gusto-mahatsafa.jpg'),
('Byantara Al Hakim Nadhif', NULL, 'XI TKJ 3', NULL, NULL, NULL, NULL, NULL, 'byantara-al-hakim-nadhif.jpg'),
('Cleosya Kapita Bilqist', NULL, 'XI TKJ 3', NULL, NULL, NULL, NULL, NULL, 'cleosya-kapita-bilqist.jpg'),
('Devina Aurelia Hapsari', NULL, 'XI TKJ 3', NULL, NULL, NULL, NULL, NULL, 'devina-aurelia-hapsari.jpg'),
('Ezar Brilliant Sugiono', NULL, 'XI TKJ 3', NULL, NULL, NULL, NULL, NULL, 'ezar-brilliant-sugiono.jpg'),
('Farhan Auliya Abrar', NULL, 'XI TKJ 3', NULL, NULL, NULL, NULL, NULL, 'farhan-auliya-abrar.jpg'),
('Flavia Annisa Kurniawan', NULL, 'XI TKJ 3', NULL, NULL, NULL, NULL, NULL, 'flavia-annisa-kurniawan.jpg'),
('Gusti Putra Khakim Khaqiqi', NULL, 'XI TKJ 3', NULL, NULL, NULL, NULL, NULL, 'gusti-putra-khakim-khaqiqi.jpg'),
('Hatta Muhlasin Luhtari', NULL, 'XI TKJ 3', NULL, NULL, NULL, NULL, NULL, 'hatta-muhlasin-luhtari.jpg'),
('Intan Alshani Raffisya', NULL, 'XI TKJ 3', NULL, NULL, NULL, NULL, NULL, 'intan-alshani-raffisya.jpg'),
('Iqbal Ilmi', NULL, 'XI TKJ 3', NULL, NULL, NULL, NULL, NULL, 'iqbal-ilmi.jpg'),
('Ivander Ardell Alvaro', NULL, 'XI TKJ 3', NULL, NULL, NULL, NULL, NULL, 'ivander-ardell-alvaro.jpg'),
('Kenza Almira Yasmin', NULL, 'XI TKJ 3', NULL, NULL, NULL, NULL, NULL, 'kenza-almira-yasmin.jpg'),
('M. Rafa Rizky Effendi', NULL, 'XI TKJ 3', NULL, NULL, NULL, NULL, NULL, 'm-rafa-rizky-effendi.jpg'),
('Mochammad Davin Al Fida', NULL, 'XI TKJ 3', NULL, NULL, NULL, NULL, NULL, 'mochammad-davin-al-fida.jpg'),
('Muhammad Faris Anshori', NULL, 'XI TKJ 3', NULL, NULL, NULL, NULL, NULL, 'muhammad-faris-anshori.jpg'),
('Muhammad Hamizan Zuhri', NULL, 'XI TKJ 3', NULL, NULL, NULL, NULL, NULL, 'muhammad-hamizan-zuhri.jpg'),
('Muhammad Kemal Faza', NULL, 'XI TKJ 3', NULL, NULL, NULL, NULL, NULL, 'muhammad-kemal-faza.jpg'),
('Muhammad Rifqi Nasywan Athallah', NULL, 'XI TKJ 3', NULL, NULL, NULL, NULL, NULL, 'muhammad-rifqi-nasywan-athallah.jpg'),
('Nazriel Abiy Putra Veangga', NULL, 'XI TKJ 3', NULL, NULL, NULL, NULL, NULL, 'nazriel-abiy-putra-veangga.jpg'),
('Nizar Zulmi Firmansyah', NULL, 'XI TKJ 3', NULL, NULL, NULL, NULL, NULL, 'nizar-zulmi-firmansyah.jpg'),
('Radine Dygtastya Rahmadhani', NULL, 'XI TKJ 3', NULL, NULL, NULL, NULL, NULL, 'radine-dygtastya-rahmadhani.jpg'),
('Rahel Maryam', NULL, 'XI TKJ 3', NULL, NULL, NULL, NULL, NULL, 'rahel-maryam.jpg'),
('Satria Banyu Seki', NULL, 'XI TKJ 3', NULL, NULL, NULL, NULL, NULL, 'satria-banyu-seki.jpg'),
('Valvizzy Piscesio Lois', NULL, 'XI TKJ 3', NULL, NULL, NULL, NULL, NULL, 'valvizzy-piscesio-lois.jpg'),
('Yohan Alim Wijaya', NULL, 'XI TKJ 3', NULL, NULL, NULL, NULL, NULL, 'yohan-alim-wijaya.jpg'),
('Ziyadatul Ilman Nafiah', NULL, 'XI TKJ 3', NULL, NULL, NULL, NULL, NULL, 'ziyadatul-ilman-nafiah.jpg');